[project]
name = "colpali"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "colpali-engine[interpretability]>=0.3.4",
    "jupyter>=1.1.1",
    "pillow>=10.4.0",
    "setuptools>=75.6.0",
    "torch>=2.5.1",
]
